all: mario_Simples cash credit
	
mario_Simples: mario_Simples.c
	gcc -ggdb -Wall -o mario_Simples mario_Simples.c -lcs50
	
cash: cash.c
	gcc -ggdb3 -std=c11 -Wall -Werror -Wformat=0 -o cash cash.c -lm -lcs50		
		
credit: credit.c
	gcc -ggdb3 -std=c11 -Wall -Werror -Wformat=0 -o credit credit.c -lm -lcs50
